version: "2"
linters:
  default: none
  enable:
    - godot
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused
    - whitespace
  settings:
    revive:
      rules:
      - name: package-comments
        disabled: true
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
