name: build dev docker image

on:
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    name: build-docker-image-dev
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: |
          tag=$(echo "${{ github.ref }}" | cut -d "/" -f3)
          sha="${{ github.sha }}"
          echo "NEW_TAG=pr-${tag}-${sha}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.cennso.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: registry.cennso.com/cennso-dev/ipsec-prometheus-exporter:${{ env.NEW_TAG }}
